name       : wavpack
version    : 5.6.0
release    : 13
source     :
    - https://github.com/dbry/WavPack/releases/download/5.6.0/wavpack-5.6.0.tar.xz : af8035f457509c3d338b895875228a9b81de276c88c79bb2d3e31d9b605da9a9
homepage   : https://www.wavpack.com
license    : BSD-3-Clause
component  :
    - multimedia.codecs
    - utils :
        - multimedia.codecs
summary    : WavPack audio compression tools
description: |
    WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
