name       : wavpack
version    : 5.1.0
release    : 5
source     :
    - http://www.wavpack.com/wavpack-5.1.0.tar.bz2 : 1939627d5358d1da62bc6158d63f7ed12905552f3a799c799ee90296a7612944
homepage   : http://www.wavpack.com
license    : BSD-3-Clause
summary    : WavPack audio compression tools
component  : multimedia.codecs
description: |
    WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode.
patterns   :
    - utils : [/usr/bin, /usr/share/man/man1]
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
