name       : wavpack
version    : 5.1.0
release    : 10
source     :
    - https://github.com/dbry/WavPack/archive/5.1.0.tar.gz : 1af7eaccbf560271013d4179d98ef6fc681a2bb3603382577eeba73d438785f4
homepage   : http://www.wavpack.com
license    : BSD-3-Clause
summary    : WavPack audio compression tools
component  : multimedia.codecs
description: |
    WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode.
patterns   :
    - utils : [/usr/bin, /usr/share/man/man1]
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
