name       : wavpack
version    : 5.4.0
release    : 11
source     :
    - https://github.com/dbry/WavPack/releases/download/5.4.0/wavpack-5.4.0.tar.xz : 4bde6a6b2a86614a6bd2579e60dcc974e2c8f93608d2281110a717c1b3c28b79
homepage   : https://www.wavpack.com
license    : BSD-3-Clause
summary    : WavPack audio compression tools
component  :
    - multimedia.codecs
    - utils :
        - multimedia.codecs
description: |
    WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
patterns   :
    - utils :
        - /usr/bin
        - /usr/share/man/man1
