name       : wavpack
version    : 4.80.0
release    : 3
source     :
    - http://www.wavpack.com/wavpack-4.80.0.tar.bz2 : 79182ea75f7bd1ca931ed230062b435fde4a4c2e0dbcad048007bd1ef1e66be9
homepage   : http://www.wavpack.com
license    : BSD-3-Clause
summary    : WavPack audio compression tools
component  : multimedia.codecs
description: |
    WavPack is a completely open audio compression format providing lossless, high-quality lossy, and a unique hybrid compression mode.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
